export const supabaseProjectId = 'jfrwlzogdrutdwdsqpub'
export const supabaseUrl = `https://${supabaseProjectId}.supabase.co`;
export const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmcndsem9nZHJ1dGR3ZHNxcHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzU2ODQwODUsImV4cCI6MTk5MTI2MDA4NX0.o_Y0yeXYeAlwsBQyh0eRs8v2gcw9BNkYR80IOVPdhBs';